"""add isDone flag to Task

Revision ID: 164bd44250f3
Revises: c91fbff56122
Create Date: 2024-02-28 00:43:37.000134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164bd44250f3'
down_revision = 'c91fbff56122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDone', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('isDone')

    # ### end Alembic commands ###
