version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_app:latest
    container_name: flask_app
    ports:
      - 5000:3000
    volumes:
      - ./server/app:/app/app
